## Python Numpy

In [1]:
## First let us import Numpy LIbrary
import numpy as np

In [14]:
agelist = [23,42,25,26,29,31]
print(type(agelist))
agearray = np.array(agelist).reshape(2,3)  ## np.array() is used to create the numpy array
print(type(agearray))
print(agearray)
print(agearray.ndim)  ## provides the dimention of the array
print(agearray.size)  ## Provides the number of elements in the array
print(agearray.shape)  ## Shape of the array

<class 'list'>
<class 'numpy.ndarray'>
[[23 42 25]
 [26 29 31]]
2
6
(2, 3)


A random module in Numpy has many functions to create random numbers.

In [15]:
# Declaring a list
agelist = list(np.random.randint(18, 45, 10))

print(agelist)
print(type(agelist))

## Creating array
agearray = np.array(agelist)

print(agearray)  # Printing the array
print(type(agearray))  # Printing the type
print(agearray.shape)

[35, 36, 32, 44, 38, 18, 44, 30, 42, 25]
<class 'list'>
[35 36 32 44 38 18 44 30 42 25]
<class 'numpy.ndarray'>
(10,)


In [16]:
## String Array
books = np.array(['Python for Data Science','Intro to Machine Learning','Intro to Deep Learning'])

print(books)  ## Printing the array
type(books)   ## Printing the Type 

['Python for Data Science' 'Intro to Machine Learning'
 'Intro to Deep Learning']


numpy.ndarray

**random()** is used to create random numbers.  It will create the random numbers from [0.0, 1.0].

In [8]:
## Creating 20 random numbers.  It will create 1-d array.
np.random.random(size=(3,4))  ## Size is an optional parameeter and it will create the random numbers for the given size

array([[0.24827786, 0.19213742, 0.24852955, 0.2682431 ],
       [0.37327547, 0.37546978, 0.814489  , 0.18824161],
       [0.92744714, 0.29742177, 0.85253286, 0.31587512]])

In [19]:
x1 = np.random.randint(10,20,5)  ## Randint is a function to generate random integers in the given range.
type(x1)
print(x1)

[16 18 14 15 13]


In [20]:
np.random.random()  ## It generates only one random number between 0 and 1.

0.8213004662805756

In [17]:
## Creating 20 random numbers.  It will create 1-d array.
np.random.random(size=(10),)

array([0.09015352, 0.41969073, 0.7342097 , 0.39119742, 0.99172101,
       0.63433028, 0.48729125, 0.10220525, 0.5400017 , 0.13573074])

In [30]:
## To generate random integer numbers in the given range and the number of elements.
x1 = np.random.randint(20,100,25).reshape(5,5)
print(x1)
print(x1.shape)
print(x1.size)
print(x1.ndim)

[[27 51 50 74 25]
 [89 47 69 66 67]
 [20 97 31 77 78]
 [33 29 33 44 92]
 [47 56 85 53 79]]
(5, 5)
25
2


In [31]:
## To generate random integer numbers in the given range and the number of elements.
x1 = np.random.randint(20,100,27).reshape(3,3,3)
print(x1)
print(x1.shape)
print(x1.size)
print(x1.ndim)

[[[98 61 53]
  [85 41 62]
  [56 30 94]]

 [[25 55 53]
  [70 90 22]
  [74 30 30]]

 [[98 66 99]
  [79 28 86]
  [93 88 96]]]
(3, 3, 3)
27
3


In [34]:
np.random.randint(-20,-10,10)  ## generating negative integers

array([-14, -12, -14, -14, -12, -13, -13, -16, -11, -11])

**rand()** is used to create random numbers between 0 and 1 in a given shape.

In [21]:
np.random.rand()

0.8441986804283775

In [6]:
## Creating array using rand()
print(np.random.rand(3,3))

## To generate a single random number
np.random.rand()

[[0.77850307 0.76480494 0.54416206]
 [0.29286049 0.69049545 0.04370611]
 [0.06614182 0.20875652 0.77488169]]


0.23260120145969643

**randint()** is used to create random integer numbers from the given range.

In [8]:
## Generating single random number
print(np.random.randint(10,100))

## Creating ramdom integers of size 25
np.random.randint(1,100,25)

34


array([52,  8, 63, 99, 64, 18, 44, 95, 50, 79,  6, 26, 81, 84, 67, 90, 72,
       66, 33, 56, 81, 74, 27, 90, 82])

In [12]:
np.random.randint(10,100,10)

array([11, 34, 77, 50, 30, 47, 99, 92, 45, 72])

In [36]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

**numpy.arange()** is also used to create sequence of  numbers.

**numpy.arange(start, stop, step, dtype)**

- start = starting number
- stop =  ending number
- step =  incremental number
- dtype = data type we want to generate; the default datatype is int

In [39]:
## Creating Odd numbers
print(np.arange(1,100,2,int))

## Creating even numbers
np.arange(0,100,2)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [43]:
## Creating Odd numbers
print(np.arange(1,100,2,float))

## Creating even numbers
np.arange(0,100,2)  # 

np.arange(0,1,0.01)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39. 41. 43. 45. 47. 49. 51. 53. 55. 57. 59. 61. 63. 65. 67. 69. 71.
 73. 75. 77. 79. 81. 83. 85. 87. 89. 91. 93. 95. 97. 99.]


array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

#### linspace()
To create evenly spaced numbers in a given range, we can use linspace function

**linspace(start, end, number_of_elements).**

- start: starting number
- end: ending number
- number_of_elements:  Number of elements to be generated

In [59]:
## Creating evenly spaced numbers using linspace
print(np.linspace(0, 100, 11))

## Creating zero array
print(np.zeros(10))

## Creating 1 arragy
print(np.ones(10))

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [50]:
(100-0)/(10-1)

11.11111111111111

In [60]:
## Creating arbitrary 3 x 3 array using empty
print(np.empty((3,3), dtype=int))

[[11 11 11]
 [11 11 11]
 [11 11 11]]


In [64]:
## Creating 3 x 3 matrix using fill_value
print(np.full((3,4),fill_value = 5))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [66]:
## Creating an identity matrix
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [122]:
## np.eye(Rows, Columns, Identity_Index)
np.eye(4,5,0)  ## It will also create the identity matrix with identity in the kth index

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [123]:
np.eye(4,5,1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [126]:
np.eye(4,5,-1)  ## the -kth index is for the column identity

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [69]:
l1 = [10,20,25,10.25]
np.array(l1)

array([10.  , 20.  , 25.  , 10.25])

### Array Attributes

In [70]:
## Creating an array with books and its prices
books = np.array([('Python for Data science','Intro to Deep Learning','Python Handbook'),(35,55,20)])

print(books)

## Printing the shape of the array
print("The shape of the array is : ",books.shape)

## Printing the size of the array
print("The number of elements in the array is : ",books.size)

books = np.array([(1.5, 2.5,4.6),(7.9,8,9.0)])

## Printing the data type of the array
print("The data type of the array is : ",books.dtype)

## Printing the dimension of the array
print("The dimension of the array is : ",books.ndim)

[['Python for Data science' 'Intro to Deep Learning' 'Python Handbook']
 ['35' '55' '20']]
The shape of the array is :  (2, 3)
The number of elements in the array is :  6
The data type of the array is :  float64
The dimension of the array is :  2


### Array Operations

In [77]:
## Creating odd and even number arrays
oddnumber = np.array([1, 3, 5, 7]).reshape(2,2)
evennumber = np.array([8,6,2,4]).reshape(2,2)
print(oddnumber,'\n', evennumber)

## Adding two arrays
sum = oddnumber + evennumber
print("Sum of arrays : ", sum)

## Substracting even array from odd array
sub = oddnumber - evennumber
print("Odd array - Even Array : ", sub)

## Multiplying each element of odd array by 5
print("Odd array multiplied by 5 :", oddnumber * 5)

## Multiplying two arrays
print(oddnumber * evennumber)  ## This is normal element wise multiplication

## Matrix Multiplication
print(oddnumber.dot(evennumber))


[[1 3]
 [5 7]] 
 [[8 6]
 [2 4]]
Sum of arrays :  [[ 9  9]
 [ 7 11]]
Odd array - Even Array :  [[-7 -3]
 [ 3  3]]
Odd array multiplied by 5 : [[ 5 15]
 [25 35]]
[[ 8 18]
 [10 28]]
[[14 18]
 [54 58]]


In [23]:
## Matrix Multiplication
n1 = np.array([[1, 2, 4],[3,5,2]])
n2 = np.array([[3, 1],[7,2],[4,5]])

print(n1)
print(n2)

prod = n1.dot(n2)
print("\n Matrix multiplication : \n\n",prod)

[[1 2 4]
 [3 5 2]]
[[3 1]
 [7 2]
 [4 5]]

 Matrix multiplication : 

 [[33 25]
 [52 23]]


In [22]:
np.matmul(n1,n2)

array([[33, 25],
       [52, 23]])

In [24]:
n1*n2  ## this is normal multiplication

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [82]:
## Element wise multiplication
n1 = np.array([[1, 2, 4],[3,5,2]])
n2 = np.array([[3, 1, 7],[2,4,5]])

print(n1)
print(n2)

prod = n1 * n2
print("\nElementwise multiplication : \n\n",prod)

[[1 2 4]
 [3 5 2]]
[[3 1 7]
 [2 4 5]]

Elementwise multiplication : 

 [[ 3  2 28]
 [ 6 20 10]]


Elementwise Multiplication will work only with same dimension arrays.

In [23]:
## Element wise multiplication
n1 = np.array([[1, 2, 4],[3,5,2]])
n2 = np.array([[3, 1],[2,4]])


print(n1)
print(n2)

print(n1 * n2)

[[1 2 4]
 [3 5 2]]
[[3 1]
 [2 4]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [78]:
## Creating a 1D array
agearray = np.random.randint(18,35,16)
print(agearray)

print(agearray[1::4])
print(len(agearray))

## Convering 1D array to 4 x 4 array
reshaped_array = agearray.reshape(4,4)
reshaped_array

[22 23 34 19 34 23 33 19 34 21 30 21 28 22 27 23]
[23 23 21 22]
16


array([[22, 23, 34, 19],
       [34, 23, 33, 19],
       [34, 21, 30, 21],
       [28, 22, 27, 23]])

In [79]:
agearray=np.random.randint(18,35,16).reshape(4,4)
print(agearray)

[[19 26 27 27]
 [27 24 29 19]
 [24 22 22 25]
 [18 19 33 22]]


In [32]:
reshaped_array[:,0]

array([33, 29, 27, 19])

## Slicing and Indexing

- slicing[rows, columns]

In [81]:
print(agearray)

[[19 26 27 27]
 [27 24 29 19]
 [24 22 22 25]
 [18 19 33 22]]


In [82]:
## get the 3rd row from the array
agearray[2]

array([24, 22, 22, 25])

In [83]:
## Select the element 29
agearray[1,2]

29

In [84]:
## Select the elem = 35nt 29
agearray[1,2] = 35
print(agearray)

[[19 26 27 27]
 [27 24 35 19]
 [24 22 22 25]
 [18 19 33 22]]


In [87]:
agearray*5

array([[ 95, 130, 135, 135],
       [135, 120, 175,  95],
       [120, 110, 110, 125],
       [ 90,  95, 165, 110]])

In [94]:
## simple statistical values from the given array
agearray.min(), agearray.max(), agearray.std(), agearray.var()

(18, 35, 4.713262537775718, 22.21484375)

In [97]:
agearray.sum(axis=1)

array([ 99, 105,  93,  92])

In [101]:
print(agearray)
print(agearray.cumsum(axis=1))  ## Row-wise cumulative sum
print(agearray.cumsum(axis=0)) ## Column-wise cumulative sum

[[19 26 27 27]
 [27 24 35 19]
 [24 22 22 25]
 [18 19 33 22]]
[[ 19  45  72  99]
 [ 27  51  86 105]
 [ 24  46  68  93]
 [ 18  37  70  92]]
[[ 19  26  27  27]
 [ 46  50  62  46]
 [ 70  72  84  71]
 [ 88  91 117  93]]


Simple Statistical analysis

In [34]:
## Creating one dimentinal arrary
salaries = np.array([100000,75000,24000,15000,45000,16000])

## Printing the salaries array
print(salaries)

## Finding the minimum value
print("\nThe minimum Salary is : ", salaries.min())

## Finding the minimum value
print("\nThe maximum Salary is : ", salaries.max())

## The variance in salaries
print("\nThe variance in Salary is : ", salaries.var())

## The variance in salaries
print("\nThe Standard Deviation in Salary is : ", salaries.std())

[100000  75000  24000  15000  45000  16000]

The minimum Salary is :  15000

The maximum Salary is :  100000

The variance in Salary is :  1017138888.8888888

The Standard Deviation in Salary is :  31892.61495846474


In [90]:
## More mathematical functions. np.square()

## Creating an array of sides of square
side_sq = np.array([10,23,15,8,21])

## Printing the area of squares
print("The area of squares are : ", np.square(side_sq))

The area of squares are :  [100 529 225  64 441]


In [92]:
## np.power()

## Finding the volume of cubes
cube_sides = np.array([3,5,7,4,10])

## The volume of cube sides
print("\nThe volume of cube sides are : ", np.power(cube_sides, 3))


The volume of cube sides are :  [  27  125  343   64 1000]


In [35]:
## np.transpose() reverses the order of the matrix.  Suppose if we have M x N, the transpose will change it to N x M

## Creating 2 x 3 matrix
matrix = np.array([(1, 2, 3),(4, 5, 6)])

## Printing the matrix
print("The matrix is : \n",matrix)

## Printing the transpose of the matrix
print("The transposed matrix is : \n", np.transpose(matrix))

The matrix is : 
 [[1 2 3]
 [4 5 6]]
The transposed matrix is : 
 [[1 4]
 [2 5]
 [3 6]]


In [106]:
matrix = np.random.randint(10,20,16).reshape(4,4)  ## generating a 4 x 4 matrix

In [108]:
#matrix = np.random.randint(10,20,16).reshape(4,4)
print('Original Matrix','\n\n',matrix)
print('\n','Flipped Matrix','\n\n',np.flip(matrix))  ## Flipping both rows and columns

Original Matrix 

 [[17 16 19 17]
 [19 16 12 17]
 [12 14 17 15]
 [17 12 18 17]]

 Flipped Matrix 

 [[17 18 12 17]
 [15 17 14 12]
 [17 12 16 19]
 [17 19 16 17]]


In [113]:
np.flipud(matrix)  ## Only flipping the rows

array([[17, 12, 18, 17],
       [12, 14, 17, 15],
       [19, 16, 12, 17],
       [17, 16, 19, 17]])

In [115]:
np.flip(matrix,0)  ## Only flipping the rows

array([[17, 12, 18, 17],
       [12, 14, 17, 15],
       [19, 16, 12, 17],
       [17, 16, 19, 17]])

In [114]:
np.flip(matrix,1)  ## Only flipping the columns

array([[17, 19, 16, 17],
       [17, 12, 16, 19],
       [15, 17, 14, 12],
       [17, 18, 12, 17]])

In [38]:
## Concatenating array
a1 = np.array([23, 4, 76,21, 55])
a2 = np.array([150, 267, 35, 98,256, 750])

## Concatenating the array using concatenate()
a1a2 = np.concatenate([a1, a2])

## Printing the concatenated array
print("The concatenated array \n",a1a2)

The concatenated array 
 [ 23   4  76  21  55 150 267  35  98 256 750]


In [39]:
a1 = np.array([(1,2,3),(3,4,5)])
a2 = a1 * 2
print(a1)
print(a2)
a1a2 = np.concatenate([a1,a2])  ## Concatnating two 2 x 3 array.  The resultant array will be 4 x 3
print(a1a2)

a1[1,1] = 100

print(a1)

[[1 2 3]
 [3 4 5]]
[[ 2  4  6]
 [ 6  8 10]]
[[ 1  2  3]
 [ 3  4  5]
 [ 2  4  6]
 [ 6  8 10]]
[[  1   2   3]
 [  3 100   5]]


In [116]:
## Concatenating 2D array

a1 = np.array([['James', 24], ['Smith',21], ['Bob',45]])
a2 = np.array([['Amy',21],['Charles', 28]])

## Concatenating the 2D array using concatenate()
a1a2 = np.concatenate([a1, a2])   
               
## Printing the concatenated 2d Array
print("The concatenated 2D array\n",a1a2)
print("The dimension of the concatenated array is ",a1a2.shape)

The concatenated 2D array
 [['James' '24']
 ['Smith' '21']
 ['Bob' '45']
 ['Amy' '21']
 ['Charles' '28']]
The dimension of the concatenated array is  (5, 2)


In [103]:
## Using flatten() to convert multi dimentional array to a single dimention array
a1 = np.array([[150, 267], [35, 98],[256, 750]])

## Printing the array
print("The 2D array \n", a1)

## The flattened array
print("\nThe flattened array \n", np.ndarray.flatten(a1))

The 2D array 
 [[150 267]
 [ 35  98]
 [256 750]]

The flattened array 
 [150 267  35  98 256 750]


In [118]:
## Processing the array elements
print(a1)
for row in a1:
    for col in row:
        print(col)

[['James' '24']
 ['Smith' '21']
 ['Bob' '45']]
James
24
Smith
21
Bob
45


In [107]:
## Books Array
books = np.array([['Python for Data Science','Intro to Machine Learning','Intro to Deep Learning'],[35, 51.5, 43]])

## Printing the dimension of Books array
print("The dimension of 'books' array is : ",books.ndim,'\n\n')

## We can iterate the array using for loop
## Printing each element of the array using for loop
for i in books:
    print(i)
    
## Printing each element separately
print("\n\nPrinting each element in 2D array separately\n")
for i in books:
    for j in i:
        print(j)

The dimension of 'books' array is :  2 


['Python for Data Science' 'Intro to Machine Learning'
 'Intro to Deep Learning']
['35' '51.5' '43']


Printing each element in 2D array separately

Python for Data Science
Intro to Machine Learning
Intro to Deep Learning
35
51.5
43


In [1]:
a1 = [1,2,3]
a2 = [4,5,6]
a1a2 = zip(a1, a2)
for i in a1a2:
    print(i)

(1, 4)
(2, 5)
(3, 6)


The Numpy arrays are faster than lists.  We can see through an example.

In [120]:
import time

## Declaring size of an array and lists
size = 1000000

## Creating a lists
l1 = list(range(size))
l2 = list(range(size))

print(type(l1))
print(type(l2))

starttime = time.time()
resultlist = [(a * b) for a, b in zip(l1, l2)]

## Calculating the time taken for processing lists
print("The time taken for processing lists : ",(time.time() - starttime),'seconds')

<class 'list'>
<class 'list'>
The time taken for processing lists :  0.15015220642089844 seconds


In [121]:
## Creating 2 arrays
a1 = np.arange(size)
a2 = np.arange(size)
print(type(a1),type(a2))

starttime = time.time()
resultarray = a1 * a2

## Calculating the time taken for processing array
print("The time taken for processing arrays : ",(time.time() - starttime),'seconds')

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
The time taken for processing arrays :  0.00199127197265625 seconds
